name: Update Dependencies
on:
  schedule:
    # Runs at 00:00 UTC every Sunday"
    - cron: "0 0 * * 0"
  workflow_dispatch: {}
jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.UPDATER_APP_ID }}
          private_key: ${{ secrets.UPDATER_SECRET_KEY }}
      - name: Read .tool-versions
        id: versions
        uses: marocchino/tool-versions-action@v1
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ steps.versions.outputs.pnpm }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Update dependencies
        run: pnpm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: package.json,pnpm-lock.yaml
          commit-message: Update dependencies
          committer: Update Action <noreply@github.com>
          author: Romeo Van Snick <romeo@romeovansnick.be>
          branch: update-dependencies
          delete-branch: true
          base: main
          title: Update dependencies
          body: Update pnpm dependencies. Generated by the `Update Dependencies` workflow.
          assignees: romeovs
          labels: dependencies
